### ISSUE TITLE
Disassembly of AVR firmware

### ISSUE THREAD

**Issue by Darkkey** [hteso/iaito#15]
Trying to open attached file (ex3.4.bin in [avr.zip](https://github.com/hteso/iaito/files/879828/avr.zip)
), all options are default, except arch = AVR.

```
$ ./Iaito
QMetaObject::connectSlotsByName: No matching signal for on_backButton_clicked()
BITS 8
[opcode elpm @aa returned 0 cycles. sym. and entry0 (aa)
opcode st @ac returned 0 cycles.
opcode st @171a returned 0 cycles.
opcode std @174c returned 0 cycles.
opcode lds @2e32 returned 0 cycles.
opcode std @31fc returned 0 cycles.
opcode elpm @36ce returned 0 cycles.
Invalid address 0x390a. Try with io.va=true
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ]
[aav: Cannot find section at this address
aav: Cannot find section at this address
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
Cannot open project info (/Users/key/.config/radare2/projects/ex3.4.bin/rc)
Cannot retrieve information for project '/Users/key/.config/radare2/projects/ex3.4.bin/rc'
Floating point exception: 8
```

**Comment by xarkes** [comment]
I have also a Floating exception like so:
```
$ ./iaito  
QRCore::tryFile: Cannot open file?
libpng warning: iCCP: known incorrect sRGB profile
QMetaObject::connectSlotsByName: No matching signal for on_backButton_clicked()
libpng warning: iCCP: known incorrect sRGB profile
FILE OPEN (/bin/ls)
BITS 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
r_config_set: variable 'esil.stacksize' not found
r_config_set: variable 'io.raw' not found
WARNING: file.path changed: /usr/bin/ls => malloc://983040
[1]    32459 floating point exception (core dumped)  ./iaito
```

**Comment by trufae** [comment]
What about posting a backtrace at least? Having disasm and register state would be incredible

**Comment by trufae** [comment]
The only thing i can guess here is that this is a div by zero

**Comment by xarkes** [comment]
Something like this ?
```
 [----------------------------------registers-----------------------------------]
RAX: 0x5c ('\\')
RBX: 0x5f3994c5 
RCX: 0x0 
RDX: 0x0 
RSI: 0x6 
RDI: 0x4aa67e --> 0x6600736b636f6c62 ('blocks')
RBP: 0x5c ('\\')
RSP: 0x7fffffffcc60 --> 0x18 
RIP: 0x44f6a8 (<_ZN11GraphicsBar8fillDataEv+2216>:	idiv   r15d)
R8 : 0x165efe0 --> 0x0 
R9 : 0x0 
R10: 0x9 ('\t')
R11: 0x7ffff44ef330 (<_ZNK8QVariant5toIntEPb>:	push   r12)
R12: 0x4 
R13: 0x5 
R14: 0x7fffffffceb0 --> 0x165efe0 --> 0x0 
R15: 0x0
EFLAGS: 0x10206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x44f6a2 <_ZN11GraphicsBar8fillDataEv+2210>:	mov    r15d,eax
   0x44f6a5 <_ZN11GraphicsBar8fillDataEv+2213>:	mov    eax,ebp
   0x44f6a7 <_ZN11GraphicsBar8fillDataEv+2215>:	cdq    
=> 0x44f6a8 <_ZN11GraphicsBar8fillDataEv+2216>:	idiv   r15d
   0x44f6ab <_ZN11GraphicsBar8fillDataEv+2219>:	mov    DWORD PTR [rsp+0x18],eax
   0x44f6af <_ZN11GraphicsBar8fillDataEv+2223>:	call   0x41ff90 <_ZN7QString16fromAscii_helperEPKci@plt>
   0x44f6b4 <_ZN11GraphicsBar8fillDataEv+2228>:	mov    rbx,QWORD PTR [rsp+0xf0]
   0x44f6bc <_ZN11GraphicsBar8fillDataEv+2236>:	mov    QWORD PTR [rsp+0x250],rax
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffcc60 --> 0x18 
0008| 0x7fffffffcc68 --> 0x7fffffffcd70 --> 0x1660630 --> 0x7ffff459dde0 --> 0xffffffff 
0016| 0x7fffffffcc70 --> 0x1944310 --> 0x1940f80 ("sub.dcgettext_f92")
0024| 0x7fffffffcc78 --> 0x404030 --> 0x0 
0032| 0x7fffffffcc80 --> 0xe2d6f0 --> 0x7ffff586cb18 --> 0x7ffff5228c00 (mov    rdi,QWORD PTR [rdi+0x8])
0040| 0x7fffffffcc88 --> 0x7fffffffcec0 --> 0xb511d0 --> 0x2b00000001 
0048| 0x7fffffffcc90 --> 0xcdd7d0 --> 0x7ffff588d8f0 --> 0x7ffff54948d0 (<_ZNK14QGraphicsScene10metaObjectEv>:	mov    rdi,QWORD PTR [rdi+0x8])
0056| 0x7fffffffcc98 --> 0x7fffffffcee0 --> 0x4a4affff00000001 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGFPE
0x000000000044f6a8 in GraphicsBar::fillData() ()
gdb-peda$ bt
#0  0x000000000044f6a8 in GraphicsBar::fillData() ()
#1  0x0000000000421166 in MainWindow::setup_mem() ()
#2  0x000000000042586e in MainWindow::updateFrames() ()
#3  0x00000000004325fc in OptionsDialog::anal_finished() ()
#4  0x00007ffff44dbba9 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff51d8ecb in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff519134c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff5198b61 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff44af440 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#9  0x00007ffff44b1bcd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#10 0x00007ffff4503c43 in  () at /usr/lib/libQt5Core.so.5
#11 0x00007fffec87a5a7 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007fffec87a810 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007fffec87a8bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff450404f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#15 0x00007ffff44ad89a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#16 0x00007ffff537f917 in QDialog::exec() () at /usr/lib/libQt5Widgets.so.5
#17 0x000000000042fb79 in NewFileDialog::on_loadFileButton_clicked() ()
#18 0x000000000049a563 in NewFileDialog::qt_metacall(QMetaObject::Call, int, void**) ()
#19 0x00007ffff44daee4 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/libQt5Core.so.5
#20 0x00007ffff5279d02 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff5279f54 in  () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff527b347 in  () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff527b524 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff51d8cd8 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff519134c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff51998c5 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff44af440 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#28 0x00007ffff51980cd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff51f33e6 in  () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff51f5e03 in  () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff519134c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff5198b61 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff44af440 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#34 0x00007ffff49fcd53 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#35 0x00007ffff49fe8c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#36 0x00007ffff49da44b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#37 0x00007fffe388c9e0 in  () at /usr/lib/libQt5XcbQpa.so.5
#38 0x00007fffec87a5a7 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#39 0x00007fffec87a810 in  () at /usr/lib/libglib-2.0.so.0
#40 0x00007fffec87a8bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff450404f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#42 0x00007ffff44ad89a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#43 0x00007ffff44b5de4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#44 0x000000000042023e in main ()
#45 0x00007ffff35f1511 in __libc_start_main () at /usr/lib/libc.so.6
#46 0x00000000004203fa in _start ()
```

**Comment by trufae** [comment]
Yes thanks
